### ISSUE TITLE
[Task]: Performance optimizations (Lighthouse)

### ISSUE THREAD

**Issue by elliotBraem** [keypom/keypom-events-app#70]
### Overview

Let's optimize the performance of the application.

Here's our benchmark report:
https://lighthouse-metrics.com/lighthouse/checks/33703ac2-fd1e-41a6-a9b2-d3b241a307c2/runs/4afbe2e9-99e4-402e-b0a5-7d5b2175d65d

![Screenshot 2024-09-04 at 9 53 50 AM](https://github.com/user-attachments/assets/08e2a215-5c22-4e69-ba58-3f1ccfd34a99)

### Details

Areas I think could be improved:

- [x] #28 -- should help with first load
- [x] #71 -- should help with chunk size
- [ ] share useQuery for alerts, journeys, collectibles, rather than calling it in the page itself (aka, useQuery -> useAlerts), also better retries and cache times
- [x] #58, should remove some dead code
- [ ] moving react query client closer to the code that needs it
- [ ] move chakra further up the stack

### Acceptance Criteria

- Regression tests pass
